/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Friend = IDL.Record({
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'facebookId' : IDL.Text,
  'mobile' : IDL.Text,
});
export const GalleryEvent = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'eventName' : IDL.Text,
});
export const PDFDocument = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Post = IDL.Record({
  'categoryId' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'authorId' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const YouTubeVideo = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'youtubeUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'batch' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'postId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createFriend' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createGalleryEvent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'createPDFDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deleteFriend' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryEvent' : IDL.Func([IDL.Text], [], []),
  'deletePDFDocument' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteYouTubeVideo' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'getAllGalleryEvents' : IDL.Func([], [IDL.Vec(GalleryEvent)], ['query']),
  'getAllPDFDocuments' : IDL.Func([], [IDL.Vec(PDFDocument)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'toggleLike' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateFriend' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateGalleryEvent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'updatePDFDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Friend = IDL.Record({
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'facebookId' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const GalleryEvent = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'eventName' : IDL.Text,
  });
  const PDFDocument = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Post = IDL.Record({
    'categoryId' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'authorId' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const YouTubeVideo = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'youtubeUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'batch' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'postId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createFriend' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createGalleryEvent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'createPDFDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'createYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deleteFriend' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryEvent' : IDL.Func([IDL.Text], [], []),
    'deletePDFDocument' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteYouTubeVideo' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'getAllGalleryEvents' : IDL.Func([], [IDL.Vec(GalleryEvent)], ['query']),
    'getAllPDFDocuments' : IDL.Func([], [IDL.Vec(PDFDocument)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'toggleLike' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateFriend' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateGalleryEvent' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'updatePDFDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };