/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string }
export interface Comment {
  'id' : string,
  'authorId' : string,
  'body' : string,
  'createdAt' : bigint,
  'postId' : string,
}
export interface Friend {
  'name' : string,
  'photoUrl' : string,
  'facebookId' : string,
  'mobile' : string,
}
export interface GalleryEvent {
  'imageUrls' : Array<string>,
  'eventName' : string,
}
export interface PDFDocument {
  'title' : string,
  'description' : string,
  'fileUrl' : string,
}
export interface Post {
  'categoryId' : string,
  'title' : string,
  'likeCount' : bigint,
  'authorId' : string,
  'body' : string,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
}
export interface UserProfile { 'name' : string, 'batch' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YouTubeVideo {
  'title' : string,
  'description' : string,
  'youtubeUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], undefined>,
  'createFriend' : ActorMethod<[string, string, string, string], undefined>,
  'createGalleryEvent' : ActorMethod<[string, Array<string>], undefined>,
  'createPDFDocument' : ActorMethod<[string, string, string], undefined>,
  'createPost' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    undefined
  >,
  'createYouTubeVideo' : ActorMethod<[string, string, string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deleteFriend' : ActorMethod<[string], undefined>,
  'deleteGalleryEvent' : ActorMethod<[string], undefined>,
  'deletePDFDocument' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteYouTubeVideo' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllFriends' : ActorMethod<[], Array<Friend>>,
  'getAllGalleryEvents' : ActorMethod<[], Array<GalleryEvent>>,
  'getAllPDFDocuments' : ActorMethod<[], Array<PDFDocument>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllYouTubeVideos' : ActorMethod<[], Array<YouTubeVideo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPost' : ActorMethod<[string], Array<Comment>>,
  'getLikeCount' : ActorMethod<[string], bigint>,
  'getPostBySlug' : ActorMethod<[string], [] | [Post]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'incrementVisitorCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
  'toggleLike' : ActorMethod<[string], bigint>,
  'updateCategory' : ActorMethod<[string, string], undefined>,
  'updateFriend' : ActorMethod<[string, string, string, string], undefined>,
  'updateGalleryEvent' : ActorMethod<[string, Array<string>], undefined>,
  'updatePDFDocument' : ActorMethod<[string, string, string], undefined>,
  'updatePost' : ActorMethod<
    [string, string, string, string, Array<string>],
    undefined
  >,
  'updateYouTubeVideo' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];